name: PROXY Updater

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-26.04
    steps:
    - uses: actions/checkout@v6
    - name: Install Python 3
      uses: actions/setup-python@v6
      with:
        python-version: 3.13
    - name: Install dependencies
      run: |
        pipx install proxy-check-i --force
    - run: token=${{secrets.TOKEN}} proxy-check-i
    - name: Commit files
      run: |
        git config --local user.email ${{ secrets.GIT_EMAIL }}
        git config --local user.name ${{ secrets.GIT_NAME }}
        git commit -am "Updated Proxies"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
